# Generated by Django 3.2.5 on 2021-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='comment',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
